# Generated by Django 4.2 on 2025-03-05 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=500)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('tickets_booked', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapi.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketapi_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
