# Generated by Django 4.2 on 2025-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
