# Generated by Django 4.2 on 2025-03-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0002_booking_number_of_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_tickets',
            new_name='quantity',
        ),
    ]
