# Generated by Django 4.2 on 2025-03-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0003_rename_number_of_tickets_booking_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='quantity',
            new_name='num_tickets',
        ),
    ]
