# Generated by Django 4.2 on 2025-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0004_rename_quantity_booking_num_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='available_tickets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concert',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
