# Generated by Django 4.2 on 2025-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
